# Generated by Django 4.0.5 on 2022-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'on loan'), ('a', 'Available')], default='a', help_text='Book availability', max_length=1),
        ),
    ]
