# Generated by Django 4.0.5 on 2022-08-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_author_options_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed_books',
            fields=[
                ('bookinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite.bookinstance')),
            ],
            bases=('mysite.bookinstance',),
        ),
    ]
