# Generated by Django 4.0.5 on 2022-08-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_borrowed_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowed_books',
        ),
    ]
